---
title: "Untitled"
author: "Keith Lewis"
date: "2/13/2021"
output:
  flexdashboard::flex_dashboard:
    theme: yeti
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
library(knitr)
library(plotly)
library(ggplot2)
library(crosstalk)
#library(xtable)
#library(tidyverse)
#library(lubridate)
#library(kableExtra)
#library(DT)
#library(ezknitr)
#library(here)
source("simpleLRP_dat.R")
shD <- SharedData$new(df_lag)
```

# Crosstalk with scatter plots
- Cheng approach - great but not plotly

Column
-------------------------------------

```{r}
library(d3scatter)
shared_iris <- SharedData$new(iris)
bscols(
  d3scatter(shared_iris, ~Petal.Length, ~Petal.Width, ~Species, width="100%", height=300),
  d3scatter(shared_iris, ~Sepal.Length, ~Sepal.Width, ~Species, width="100%", height=300)
)
```

# Crosstalk with sliders

Row
-------------------------------------

```{r}
bscols(widths = c(3, NA, NA), 
       list(filter_slider("year", "Year", shD, ~year)),
  Scatter1(df = shD, xaxis = year, yaxis = avg_densityt_2, colour = NULL, 
           c1 = "Rank: ", c2 = "Year: ", c3 = "Density: ", xlab = "Year", 
           ylab = "Larval Density (#/m^-3)",
           filename = "figs/2-cond-year-rank.pdf", save = "no"),
  Scatter1(df = shD, xaxis = year, yaxis = tice, colour = NULL, 
           c1 = "Rank: ", c2 = "Year: ", c3 = "tice: ", 
           xlab = "Year", ylab = "Ice retreat (tice - DOY)",
           filename = "figs/2-cond-year-rank.pdf", save = "no")
)
```

# GGally + highlight

Column
-------------------------------------

```{r out.width = '80%', out.height = '80%'}

df_lag %>%
  select(abundance_med, avg_densityt_2, tice, cond_lagt_1,  mat2t_1) %>%
  GGally::ggpairs() %>%
  ggplotly() %>%
  highlight(on = "plotly_selected", off = "plotly_doubleclick")
```


# ggplotly with highlight "selected"
highlight only seems to work once

Column
-------------------------------------

```{r}
a <- Scatter1(df = shD, xaxis = year, yaxis = avg_densityt_2, colour = NULL, 
           c1 = "Rank: ", c2 = "Year: ", c3 = "Density: ", xlab = "Year", 
           ylab = "Larval Density (#/m^-3)",
           filename = "figs/2-cond-year-rank.pdf", save = "no")
b <- Scatter1(df = shD, xaxis = year, yaxis = tice, colour = NULL, 
           c1 = "Rank: ", c2 = "Year: ", c3 = "tice: ", 
           xlab = "Year", ylab = "Ice retreat (tice - DOY)",
           filename = "figs/2-cond-year-rank.pdf", save = "no")

subplot(a,b) %>% highlight(on = 'plotly_selected', off = 'plotly_deselect') %>% hide_legend()
```

# qplot with highlight
works - to unselect, just select all data
```{r}

d <- highlight_key(mtcars)
s <- subplot(
  qplot(data = d, x = mpg, y = wt),
  qplot(data = d, x = mpg, y = vs)
)

highlight(s, "plotly_selected")
```

# Highlight with click
-highlight https://tutorials.cpsievert.me/20180711/#21

Column
-------------------------------------

```{r}
p <- ggplot(txhousing) + geom_line(aes(date, median, group = city))
ggplotly(p)
```


```{r}
p <- ggplot(txhousing) + geom_line(aes(date, median, group = city, text = city))
ggplotly(p, tooltip = "text")
```

Column
-------------------------------------

```{r}
tx <- highlight_key(txhousing, ~city)
p <- ggplot(tx) + geom_line(aes(date, median, group = city, text = city))
gg <- ggplotly(p, tooltip = "text")
highlight(gg, on = "plotly_click")
```


```{r}
tx <- highlight_key(txhousing, ~city)
p <- ggplot(tx) + geom_line(aes(date, median, group = city, text = city))
gg <- ggplotly(p, tooltip = "text")
highlight(gg, on = "plotly_hover", selectize = TRUE, dynamic = TRUE)
```


# Highlight  link data sets

```{r}
temp <- txhousing %>%
  group_by(city) %>%
  summarize(avg = mean(sales), med = mean(median))


test <- left_join(txhousing, temp, by = "city")
tx <- highlight_key(test, ~city)

dots <- ggplot(data = tx, aes(x = avg, y = city, text = paste(
  "median: ", median, "\n",
  "mean: ", avg, "\n",
  "city: ", city, "\n",  
  sep = ""
))) + geom_point()
dots <- ggplotly(dots, tooltip = "text")

p2 <- ggplot(tx) + geom_line(aes(date, median, group = city, text = city))
lines <- ggplotly(p2, tooltip = "text")

subplot(dots, lines, titleX = TRUE, titleY = TRUE) %>% 
  highlight("plotly_hover")

```


# Highlight with facet wrap - hover

Column
-------------------------------------

```{r}
tx <- txhousing %>%
  select(city, year, month, median) %>%
  filter(city %in% c("Galveston", "Midland", "Odessa", "South Padre Island"))
TX <- highlight_key(tx, ~year)
p <- ggplot(TX, aes(month, median, group = year)) + geom_line() +
  facet_wrap(~city, ncol = 2)
ggplotly(p, tooltip = "year")
highlight(.Last.value, on = "plotly_hover", defaultValues = 2006)
```


# Highlight with subplots - selected

```{r}
library(plotly)
d <- highlight_key(mpg)
dots <- plot_ly(d, color = ~class, x = ~displ, y = ~cyl)
boxs <- plot_ly(d, color = ~class, x = ~class, y = ~cty) %>% 
  add_boxplot()
bars <- plot_ly(d, colors = "Set1", x = ~class, color = ~class)
subplot(dots, boxs, titleX = TRUE, titleY = TRUE) %>%
  subplot(bars, nrows = 2, titleX = TRUE, titleY = TRUE) %>%
  layout(
    barmode = "overlay",
    showlegend = FALSE
  ) %>%
  highlight("plotly_selected")
```


# Highlight with 2 subplots - selected

```{r}
d <- highlight_key(mtcars)
sp <- plot_ly(d, x = ~mpg, y = ~disp) %>% 
  add_markers(color = I("black"))
# 'statistical trace types'
hist <- plot_ly(d, x = ~factor(cyl)) %>% add_histogram(color = I("black"))
box <- plot_ly(d, y = ~disp, color = I("black")) %>% add_boxplot(name = " ")
violin <- plot_ly(d, y = ~disp, color = I("black")) %>% add_trace(type = "violin", name = " ")
subplot(sp, box, violin, shareY = TRUE, titleX = TRUE, titleY = TRUE) %>%
  subplot(hist, widths = c(.75, .25), titleX = TRUE, titleY = TRUE) %>%
  layout(
    barmode = "overlay", 
    title = "Click and drag scatterplot",
    showlegend = FALSE
  ) %>%
  highlight("plotly_selected")
```